### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by leyluj** [bychwa/lemonade#1]
Hey man,

I don't understand the use case, if possible can you elaborate it in the README.md

Cheers,

🍻

**Comment by bychwa** [comment]
I will try to be more explicit in the readme file. But basically for amazon web services, you can decide to separate accounts for different purposes and assigning roles for each. For example, you can have account for infrastructure people, developers, accountants, managers etc all of which can have roles that determines what these accounts can see. Individuals( or as they call root accounts) can be assigned to these accounts/profiles based on their credentials so that they get revolved the moment they change roles etc. You can read more about it from: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html

Together with that, you can have optional/mandatory multi-factor authentication (MFA). With which, every time you want to sign in with your AWS credentials, you must provide a one time token code from your mobile device so as to increase security. You can read more here: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa.html

So, this app helps you manage all of the above cases to interchange and get fresh new credentials; with correct roles and MFA authenticated when trying to make api calls from your local machine.
